name: Delete Artifacts

on:
  workflow_dispatch:  # Manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all artifacts
        id: artifacts
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
          | jq '.artifacts[] | select(.name=="github-pages") | .id' > artifact_ids.txt

      - name: Delete all github-pages artifacts
        run: |
          for artifact_id in $(cat artifact_ids.txt); do
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${artifact_id}";
          done
