name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Replace with your main branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' # Replace with your Ruby version if different

      # Step 3: Update RubyGems
      - name: Update RubyGems
        run: gem update --system

      # Step 4: Install Jekyll and Bundler dependencies
      - name: Install dependencies
        run: bundle install

      # Step 5: Build the site
      - name: Build the site
        run: bundle exec jekyll build

      # Step 6: Add a .nojekyll file to bypass GitHub Pages Jekyll processing
      - name: Disable Jekyll processing
        run: touch ./_site/.nojekyll

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Path to the built site
          publish_branch: gh-pages  # Branch used for GitHub Pages deployment


