name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Replace with your default branch if it's not "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install dependencies
        run: |
          gem update --system
          bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Debug files in _site
        run: ls -R ./_site

      - name: Disable Jekyll processing
        run: touch ./_site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages



